# Generated by Django 5.0 on 2024-01-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catedratico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('dpi', models.CharField(max_length=15, unique=True)),
                ('is_account', models.BooleanField(default=False)),
                ('is_catedratico', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
