# Generated by Django 4.0 on 2024-01-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0002_catedratico'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
    ]
