# Generated by Django 4.0 on 2024-01-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='catedratico',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catedratico',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catedratico',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
