# Generated by Django 4.0 on 2024-01-11 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('accounts2', '0002_catedratico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('costo', models.PositiveIntegerField()),
                ('horario', models.CharField(max_length=20)),
                ('cupo', models.PositiveIntegerField()),
                ('cat_image', models.ImageField(upload_to='photos/cursos')),
                ('descripcion', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.categorias')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts2.catedratico')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
