# Generated by Django 4.0 on 2024-01-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0005_catedratico_is_admin_catedratico_is_staff_and_more'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='catedratico',
            field=models.ForeignKey(limit_choices_to={'is_catedratico': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts2.account'),
        ),
    ]
